language: node_js
node_js:
- '10'
- '12'
- 'node'
# Build all branches
branches:
  only:
  - gh-pages
  - /.*/
before_install:
- npm i -g npm@latest
install:
- npm ci
before_script:
# Rebuild Prism
- npx gulp
# Detect changes
# First, we stage all changes and then detect if there is anything staged
- git add --all && git diff-index --cached HEAD --stat --exit-code ||
  (echo && echo "The above files changed because the build is not up to date." && echo "Please rebuild Prism." && exit 1)
script: npm test
deploy:
  provider: npm
  email: lea@verou.me
  api_key:
    secure: TjRcXEr7Y/9KRJ4EOEQbd2Ij8hxKj8c/yOpEROy2lTYv6QH9x46nFDgZEE3VHfp/nnBUYpC47dRaSxiUj8H5rtkMNCZrREZu1n1zahmzP6dI6kCj+H3GiY7yw/Jhdx3uvQZHwknW2TJ/YRsLeQsmMSG2HnJobY9Zn4REX5ccP2E=
  on:
    tags: true
    repo: PrismJS/prism
